config/routes.rb
Rails.application.routes.draw do
  resources :sales

  resources :products

  resources :subscriptions, only: [:index, :new, :create]

  devise_for :users

  get   '/buy/:permalink',  to: 'transactions#new',      as: :show_buy
  post  '/buy/:permalink',  to: 'transactions#create',   as: :buy
  get   '/pickup/:guid',    to: 'transactions#pickup',   as: :pickup
  get   '/download/:guid',  to: 'transactions#download', as: :download

  match '/iframe/:permalink' => 'transactions#iframe', via: :get, as: :buy_iframe

  mount StripeEvent::Engine => '/stripe-events'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	skip_before_action :authenticate_user!
	before_filter :strip_iframe_protection

	

	def new
		@product = Product.find_by!(permalink: params[:permalink])
		@sale = Sale.new(product_id: @product.id)
		set_page_title "Buy #{@product.name}"
	end

	def iframe
		@product = Product.find_by!(permalink: params[:permalink])
		@sale = Sale.new(product_id: @product.id)
	end		

	def show
		@sale = Sale.find_by!(guid: params[:guid])
		@product = @sale.product
	end

	def pickup
		@sale = Sale.find_by!(guid: params[:guid])
		@product = @sale.product
	end

	def create
		product = Product.find_by!(permalink: params[:permalink])

		token = params[:stripeToken]

		sale = Sale.new do |s|
			s.amount =	product.price,
			s.product_id = product.id,
			s.stripe_token = token,
			s.email = params[:email]
		end

		if sale.save
			StripeCharger.perform_async(sale.guid)
			render json: { guid: sale.guid }
		else
			errors = sale.errors.full_messages
			render json: {
				error: errors.join(" ")
			}, status: 400
		end
	end

	def status
		sale = Sale.find_by!(guid: params[:guid])

		render json: {status: sale.state }
	end


	def download
		@sale = Sale.find_by!(guid: params[:guid])

		resp = HTTParty.get(@sale.product.file.url)

		filename = @sale.product.file.url
		send_data resp.body,
			:filename => File.basename(filename),
			:content_type => resp.headers['Content-Type']			
	end

private
	def strip_iframe_protection
		response.headers.delete('X-Frame-Options')			
	end	

	def find_product
		@product = Product.find_by!(permalink: params[:permalink])
	end
	
end

app/views/transactions/_form.html.erb
<h1><%= @product.name %></h1>

<%= @product.description.html_safe %>

<% if @error %>
<%= @error %>
<% end %>

<p>Price: <%= formatted_price(@product.price) %></p>

<div class="well" style="margin-left: 0px; position: relative; min-width: 650px; min-height: 180px; max-height: 180px">
  <%= form_tag buy_path(permalink: @product.permalink), :class => '', :id => 'payment-form' do %>
    <div class="row">
    </div>
    <div class="row">
      <div style="position: absolute; left: 20px">
        <label class="control-label" for="email">Email</label>
        <input type="email" name="email" id="email" placeholder="you@example.com" style="width: 25em"/>
      </div>
      <div style="position: absolute; left: 400px">
        <label class="control-label" for="number">Card Number</label>
        <input type="text" size="20" data-stripe="number" id="number" placeholder="**** **** **** ****" pattern="[\d ]*" style="width: 18em"/>
      </div>
    </div>
    <div class="row" style="margin-top: 65px">
      <div style="position: absolute; left: 20px">
        <label class="control-label" for="cvc">CVC</label>
        <input type="text" style="width: 3em" size="3" data-stripe="cvc" id="cvc" placeholder="***" pattern="\d*"/>
        <img id="card-image" src="credit.png" style="height: 30px; padding-left: 10px; margin-top: -10px">
      </div>
      <div style="position: absolute; left: 150px">
        <label class="control-label">Exp (MM/YYYY)</label>
        <input style="width: 2em" type="text" size="2" id="exp-month" data-stripe="exp-month" placeholder="MM" pattern="\d*"/>
        <span> / </span>
        <input style="width: 3em" type="text" size="4" id="exp-year" data-stripe="exp-year" placeholder="YYYY" pattern="\d*"/>
      </div>
    </div>
    <div class="row" style="margin-top: 70px">
      <div class="price" style="position: absolute; left: 20px;"><%= price %></div>
      <div style="position: absolute; left: 400px">
        <button type="submit" class="btn btn-primary btn-large">Buy Now</button>
      </div>
    </div>
  <% end %>
</div>  

<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<script type="text/javascript">
$(function(){
  Stripe.setPublishableKey('<%= Rails.configuration.stripe[:publishable_key] %>');

  // Capture the submit event, call Stripe, and start a spinner
  $('#payment-form').submit(function(event) {
    var form = $(this);
    form.find('button').prop('disabled', true);
    Stripe.createToken(form, stripeResponseHandler);
    $('#spinner').show();
    return false;
  });

  // Handle the async response from Stripe. On success,
  // POST the form data to the create action and start
  // polling for completion. On error, display the error
  // to the customer.
  function stripeResponseHandler(status, response) {
    var form = $('#payment-form');
    if (response.error) {
      showError(response.error.message);
    } else {
      var token = response.id;
      form.append($('<input type="hidden" name="stripeToken">').val(token));
      $.ajax({
        type: "POST",
        url: "/buy/<%= permalink %>",
        data: $('#payment-form').serialize(),
        success: function(data) { console.log(data); poll(data.guid, 30) },
        error: function(data) { console.log(data); showError(data.responseJSON.error) }
      });
    }
  }

  // Recursively poll for completion.
  function poll(guid, num_retries_left) {
    if (num_retries_left == 0) {
      showError("This seems to be taking too long. Email help@example.com and reference transaction " + guid + " and we'll take a look.");
      return;
    }
    $.get("/status/" + guid, function(data) {
      if (data.status === "finished") {
        window.location = "/pickup/" + guid;
      } else if (data.status === "error") {
        showError(data.error)
      } else {
        setTimeout(function() { poll(guid, num_retries_left - 1) }, 500);
      }
    });
  }

  function showError(error) {
    var form = $('#payment-form');
    form.find('#payment-errors').text(error);
    form.find('#payment-errors').show();
    form.find('button').prop('disabled', false);
    form.find('#spinner').hide();
  }
});

</script>

app/views/transactions/iframe.html.erb
<%= render 'form', permalink: @product.permalink, sale: @sale, price: formatted_price(@product.price) %>

app/views/transactions/new.html.erb
<%= render 'form', :permalink => @product.permalink, :sale => @sale, :price => formatted_price(@product.price) %>

app/views/transactions/pickup.html.erb
<h1>Download <%= @product.name %></h1>

<p>Thanks for buying "<%= @product.name %>". You can download your purchase by clicking the link below.</p>

<p><%= link_to "Download", download_url(guid: @sale.guid) %></p>