config/routes.rb
Rails.application.routes.draw do
  resources :sales

  resources :products

  resources :subscriptions, only: [:index, :new, :create]

  devise_for :users

  get   '/buy/:permalink',  to: 'transactions#new',      as: :show_buy
  post  '/buy/:permalink',  to: 'transactions#create',   as: :buy
  get   '/pickup/:guid',    to: 'transactions#pickup',   as: :pickup
  get   '/download/:guid',  to: 'transactions#download', as: :download

  match '/iframe/:permalink' => 'transactions#iframe', via: :get, as: :buy_iframe

  mount StripeEvent::Engine => '/stripe-events'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  has_paper_trail
  
  include AASM

  aasm column: 'state' do 
    state :pending, initial: true
    state :processing
    state :finished
    state :errored

    event :process, after: :charge_card do 
      transitions from: :pending, to: :processing
    end

    event :finish do 
      transitions from: :processing, to: :finished
    end

    event :fail do 
      transitions from: :processing, to: :errored
    end
  end

  belongs_to :product

  before_create :populate_guid

  private
  def populate_guid
  			self.guid = SecureRandom.uuid()
  end

  def charge_card
    begin
      save!
      charge = Stripe::Charge.create(
        amount: self.amount,
        currency: "usd",
        card: self.stripe_token,
        description: self.email
      )
      balance = Stripe::BalanceTransaction.retrieve(charge.balance_transaction)
      self.update(
        stripe_id:        charge.id,
        card_expiration:  Date.new(charge.card.exp_year, charge.card.exp_month, 1),
        fee_amount:       balance.fee
      )
      self.finish!
    rescue Stripe::StripeError => e
      self.update_attributes(error: e.message)
      self.fail!
    end
  end # charge_card
end # class

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:email, :guid, :product_id, :stripe_id)
    end
end

app/views/sales/_form.html.erb
<%= form_for(sale) do |f| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :guid %><br>
    <%= f.text_field :guid %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :stripe_id %><br>
    <%= f.text_field :stripe_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Guid</th>
      <th>Product</th>
      <th>Stripe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.email %></td>
        <td><%= sale.guid %></td>
        <td><%= sale.product %></td>
        <td><%= sale.stripe_id %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>
<table>
	<tr>
		<th>Key</th>
		<th>Value</th>
	</tr>
	<% @sale.attributes.sort.each do |key, value| %>
	<tr>
		<td><%= key %></td>
		<td><%= value %></td>
	</tr>
	<% end %>
</table>

<h2>History</h2>
<table class="table table-striped table-bordered table-condensed table-hover sans">
	<thead>
		<tr>
			<th>Timestamp</th>
			<th>Event</th>
			<th>Changes</th>
		</tr>
	</thead>
	<tbody>
		<% @sale.versions.each do |version| %>
			<tr>
				<td><%= version.created_at %></td>
				<td><%= version.event %></td>
				<td>
					<% version.changeset.sort.each do |key, value| %>
						<b><%= key %></b>: <%= value[0] %> to <%= value[1] %><br>
					<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'Stripe', "https://manage.stripe.com/payments/#{@sale.stripe_id}" %>
<%= link_to 'Back', sales_path %>